---
title: "Division I Baseball Ratings"
author: "Bristol Priebe"
date: "4-8-2022"
categories: ["Baseball"]
tags: ["NCAA Baseball", "Division I", "Baseball", "College Baseball"]
output: html_document
---

[Division I](https://fieldhouseanalytics.com/ratings/div1/) | [Division II](https://fieldhouseanalytics.com/ratings/div2/) | [Division III](https://fieldhouseanalytics.com/ratings/div3/) |
[NAIA](https://fieldhouseanalytics.com/ratings/naia/)

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(dplyr)
library(htmltools)
library(kableExtra)
library(knitr)
scoresList <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 Massey Scores.csv")
scoresList <- scoresList[!is.na(scoresList$Date),]
scoresList$Date <- as.Date(scoresList$Date, format = "%m/%d/%Y")
scoresList <- scoresList[order(scoresList$Date),]
ratingsDate <- scoresList$Date[nrow(scoresList)]
```

**Ratings through `r ratingsDate`**

```{r echo=FALSE, warning=FALSE, message=FALSE}

#ratings <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 Current Ratings - D-I.csv")
ratings <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 Ratings + Miscellaneous Data - D-I.csv")
ratings$WL <- paste(ratings$Won, ratings$Lost, sep = "-")
ratings$vsTop25 <- paste(ratings$WvsTop25, ratings$LvsTop25, sep = "-")
ratings$vs26to50 <- paste(ratings$Wvs26to50, ratings$Lvs26to50, sep = "-")
ratings$vs51to100 <- paste(ratings$Wvs51to100, ratings$Lvs51to100, sep = "-")
ratings$vs101to200 <- paste(ratings$Wvs101to200, ratings$Lvs101to200, sep = "-")
ratings$vs201up <- paste(ratings$Wvs201plus, ratings$Lvs201plus, sep = "-")
ratings$Home <- paste(ratings$HomeW, ratings$HomeL, sep = "-")
ratings$Away <- paste(ratings$AwayW, ratings$AwayL, sep = "-")
ratings$Neutral <- paste(ratings$NeutralW, ratings$NeutralL, sep = "-")
ratings <- ratings[,c(1:2,4,5,31,6,10:11,13:14,32:39)]
sketch = htmltools::withTags(table(
  class = 'display',
  #tableHeader(ratings),
  #tableFooter(ratings),
  thead(
    tr(
      th(colspan = 6, ''), 
      th(colspan = 2, 'Strength of Schedule'),
      th(colspan = 2, 'Stength of Record'),
      th(colspan = 5, 'vs FAC Teams'),
      th(colspan = 3, 'Location')
    ),
    tr(lapply(c("Rank", "Team", "Conf", "FAC", "Rec", "RPI", "SOS", "Rk","SOR","Rk","1-25","26-50","51-100","101-200", "201+", "Home", "Away", "Neutral"), th))
    ))
    )
datatable(ratings, container = sketch, rownames = FALSE, class = "cell-border stripe", options = list(columnDefs = list(list(className = "dt-center", targets = c(0,2:17))), pageLength = 301)) %>% formatRound("CurrentRating", digits = 2) %>% formatRound("ExpWinPct", digits = 3) %>% formatRound("WinsOverExp", digits = 1) %>% formatStyle(columns = c(1:18), fontSize = '90%')
```

