---
title: "Big Ten"
slug: "big10"
author: "Bristol Priebe"
date: "4-8-2022"
categories: ["Baseball"]
tags: ["NCAA Baseball", "Division I", "Baseball", "College Baseball", "Big Ten"]
output: html_document
---



```{r echo=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(dplyr)
library(htmltools)
library(knitr)
confList <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 CUrrent Average Rating By Conference - D-I.csv")
confList <- confList[confList$Conference == "Big Ten",]
confRank <- confList$Rank
avgRating <- round(confList$AvgRating, digits = 2)
```
**Conference Rank: `r confRank`**  
**Average Rating: `r avgRating`**  
<br>
**Note: Purdue and Ohio State have only 22 conference games scheduled due to 2 cancellations**  
  


```{r echo=FALSE, warning=FALSE, message=FALSE}

projStand <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/Big Ten/Final Data Frame for Website Conference Page.csv")
projStand$CurrPct <- projStand$Won / (projStand$Won + projStand$Lost)
projStand <- projStand[order(projStand$CurrPct, decreasing = TRUE),]
projStand$Record <- paste(projStand$Won, projStand$Lost, sep = "-")
projStand$ProjRec <- paste(projStand$SimW, projStand$SimL, sep = "-")
projStand$FirstRS <- projStand$FirstRS / 10000
projStand$TopSeed <- projStand$TopSeed / 10000
projStand$Tourney <- projStand$Tourney / 10000
projStand$InFinal <- projStand$InFinal / 10000
projStand$TChamps <- projStand$TChamps / 10000
projStand <- projStand[,c(2,1,3,4,23,22,24,14,5:8,21,15:17,19,18)]
sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(colspan = 4, ''), 
      th(colspan = 2, 'Current'),
      th(colspan = 2, 'Projected'),
      th(colspan = 2, 'Strength of Schedule'),
      th(colspan = 2, 'Stength of Record'),
      th(colspan = 1, ''), 
      th(colspan = 5, 'Projections')
    ),
    tr(lapply(c("Rank", "Team", "FAC", "RPI", "Rec", "Win%", "Rec", "Win%", "SOS", "Rk", "SOR", "Rk", "Luck", "Win/Tie 1st", "#1 Seed", "Conf Tourney", "Make Final", "Champs"), th))
    ))
    )
datatable(projStand, container = sketch, rownames = FALSE, class = "cell-border stripe", options = list(columnDefs = list(list(className = "dt-center", targets = c(0,2:17)), list(orderable = FALSE, targets = c(4,6))), pageLength = 13, dom = 't')) %>% formatRound("CurrentRating", digits = 2) %>% formatRound("CurrPct", digits = 3) %>% formatRound("SimPct", digits = 3) %>% formatRound("ExpWinPct", digits = 3) %>% formatRound("Luck", digits = 1) %>% formatRound("WinsOverExp", digits = 1) %>% formatPercentage(c("FirstRS","TopSeed", "Tourney", "InFinal", "TChamps"),1)
```


