---
title: "Division I Conferences"
slug: "d1conf"
author: "Bristol Priebe"
date: "4-8-2022"
categories: ["Baseball"]
tags: ["NCAA Baseball", "Division I", "Baseball", "College Baseball"]
output: html_document

---

[Division I](https://fieldhouseanalytics.com/d1conf/) | [Division II](https://fieldhouseanalytics.com/d2conf/) | [Division III](https://fieldhouseanalytics.com/d3conf/) |
[NAIA](https://fieldhouseanalytics.com/naiaconf/)

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(dplyr)
library(htmltools)
library(knitr)
scoresList <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 Massey Scores.csv")
scoresList <- scoresList[!is.na(scoresList$Date),]
#scoresList$Date <- as.Date(scoresList$Date, format = "%m/%d/%Y")
scoresList <- scoresList[order(scoresList$Date),]
ratingsDate <- scoresList$Date[nrow(scoresList)]
```

**Ratings through `r ratingsDate`**


```{r echo=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(dplyr)
confList <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 CUrrent Average Rating By Conference - D-I.csv")
datatable(confList, extensions = "FixedColumns", colnames = c("Rank", "Conference", "Avg Rating"), rownames = FALSE, class = "cell-border stripe", width = '400px', options = list(columnDefs = list(list(className = "dt-center", targets = c(0,2))), pageLength = 31, scrollX = TRUE, scrollY = '700px')) %>% formatRound("AvgRating", digits = 2)

```


