---
title: "Division I Baseball Ratings"
author: "Bristol Priebe"
date: 2022-04-07T21:13:14-05:00
categories: ["Baseball"]
tags: ["NCAA Baseball", "Division I", "baseball"]
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(collapse = TRUE)
```

```{r echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(DT)
#library(dplyr)
ratings <- read.csv("C:/Users/Owner/Desktop/Fieldhouse Analytics/College Baseball/2022 Current Ratings - D-I.csv")
ratings <- ratings[,1:6]

x <- kable(head(ratings), col.names = c("Rank", "Team", "Conference", "Rating", "Won", "Lost"), align = "clcccc", digits = 2, row.names = FALSE) %>% kable_styling(bootstrap_options = c("striped", "condensed"), fixed_thead = T)
#, table.attr = "style='width:40%;'"
datatable(ratings, rownames = FALSE, colnames = c("Rank", "Team", "Conference", "Rating", "Won", "Lost"), class = "cell-border stripe", options = list(columnDefs = list(list(className = "dt-center", targets = c(0,2:5))), pageLength = 301)) %>% formatRound("CurrentRating", digits = 2)
```

